apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rd1knakxa-go 
  janus-idp.io/tekton: rd1knakxa-go
  backstage.io/kubernetes-id: rd1knakxa-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rd1knakxa-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml