apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rd1knakxa-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rd1knakxa-go 
  name: rd1knakxa-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rd1knakxa-go 
